language: rust
matrix:
  include:
    - rust: 1.15.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
      env: TEST_FLAGS="--features nightly"
script: ./ci/travis.sh
