[package]
name = "static_assertions"
version = "0.1.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nvzqz/static-assertions-rs"
categories = ["no-std", "rust-patterns"]
keywords = ["assert", "static"]
description = "Compile-time assertions to ensure that invariants are met."

[badges]
travis-ci = { repository = "nvzqz/static-assertions-rs" }
